<?xml version="1.0" encoding="UTF-8" ?>
 
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
 
	<xsl:output encoding="UTF-8" 
				indent="yes" 
				method="xml" 
				version="1.0"
				media-type="text/xml"/>

	<!--
		Root node (typically <record_set/>)
	-->
	<xsl:template match="/">
		<!-- start at every top-level record -->
		<xsl:apply-templates select="//XML_RECORD[TOP_LEVEL_FLAG='Y']" mode="toplevel"/>
	</xsl:template>

	<!--
		EAD Wrapper
		http://www.loc.gov/ead/tglib/elements/ead.html
	-->
	<xsl:template match="XML_RECORD" mode="toplevel">
		<ead>

			<!-- TO DO: MAPPING TO REPLACE SAMPLE CONTENT -->
			<eadheader langencoding="iso639-2b" countryencoding="iso3166-1" dateencoding="iso8601" repositoryencoding="iso15511" scriptencoding="iso15924">
				<eadid countrycode="CA" mainagencycode="CA-ON00093" encodinganalog="Identifier">2010/11</eadid>
			    <filedesc>
			        <titlestmt>
			            <titleproper>Guide to the Mildred Davenport Dance Programs and Dance School Materials</titleproper>
			        </titlestmt>
			    </filedesc>
			    <profiledesc>
			        <creation>Generated by minisis-xslt
			        	<date normal="2013-07-08">2013-07-08 19:52:UTC</date>
					</creation>
					<langusage>
						<language langcode="eng" encodinganalog="Language">English</language>
					</langusage>
			    </profiledesc>
			</eadheader>

			<frontmatter/> 	<!-- optional -->

			<archdesc level="{LEVEL_DESC}">
				<xsl:call-template name="description"/>
			</archdesc>
		</ead>
	</xsl:template>

	<!--
		Component wrapper (unnumbered)
		http://www.loc.gov/ead/tglib/elements/c.html
	-->
	<xsl:template match="XML_RECORD">
		<c level="{LEVEL_DESC}">
			<xsl:call-template name="description"/>
		</c>
	</xsl:template>

	<!--
		Template for archdesc/c
		http://www.loc.gov/ead/tglib/appendix_c.html
	-->
	<xsl:template name="description">
		<!-- May contain: accessrestrict, accruals, acqinfo, altformavail, appraisal, arrangement, bibliography, bioghist, controlaccess, custodhist, dao, daogrp, descgrp, did, dsc, fileplan, index, note, odd, originalsloc, otherfindaid, phystech, prefercite, processinfo, relatedmaterial, runner, scopecontent, separatedmaterial, userestrict -->

		<!-- TO DO: MAPPING TO REPLACE SAMPLE CONTENT -->
		<did>
			<head>Descriptive Summary</head>
			<unittitle label="Title">Mildred Davenport dance programs and dance school materials</unittitle>
			<unitdate type="inclusive" normal="1934/1942">1934-1942</unitdate>
			<unitid countrycode="us" repositorycode="cu-i" label="Collection number"><xsl:value-of select="REFD"/></unitid>
			<origination label="Creator">
				<persname rules="aacr2">Davenport, Mildred, 1900-1990</persname>
			</origination>
			<physdesc label="Extent">
				<extent>0.3 linear feet (1 box and 1 oversize folder)</extent>
			</physdesc>
			<repository label="Repository">
				<corpname>University of California, Irvine. Library. Special Collections and Archives.</corpname>
				<address>
					<addressline>Irvine, California 92623-9557</addressline>
				</address>
			</repository>
			<abstract label="Abstract">This collection comprises dance programs</abstract>
		</did>
		<descgrp>
			<head>Important Information for Users of the Collection</head>
			<accessrestrict>
				<head>Access</head>
				<p>Collection is open for research.</p>
			</accessrestrict>
			<userestrict>
				<head>Publication Rights</head>
				<p>Property rights reside with the University of California. Literary rights are
	            retained by the creators of the records and their heirs. For permissions to reproduce or
	            to publish, please contact the Head of Special Collections and Archives.</p>
			</userestrict>
			<prefercite>
				<head>Preferred Citation</head>
				<p>Mildred Davenport Dance Programs and Dance School Materials. MS-P29. Special
	            Collections and Archives, The UC Irvine Libraries, Irvine, California.</p>
			</prefercite>
			<acqinfo>
				<head>Acquisition Information</head>
				<p>Acquired, 1998.</p>
			</acqinfo>
			<processinfo>
				<head>Processing History</head>
				<p>Processed by Adrian Turner, 2001.</p>
			</processinfo>
		</descgrp>
		<bioghist>
			<bioghist>
				<head>Biography</head>
				<p>Mildred Ellen Davenport was a noted civic official and military officer</p>
				<p>During World War II, Davenport enlisted in the Army as a captain.</p>
			</bioghist>
		</bioghist>
		<scopecontent>
			<head>Collection Scope and Content Summary</head>
			<p>The collection is arranged topically. Materials are arranged chronologically
	            within each topical grouping whenever possible.</p>
		</scopecontent>
		<controlaccess>
			<head>Indexing Terms</head>
			<p>The following terms have been used to index the description of this collection
	            in the library's online public access catalog.</p>
			<controlaccess>
				<head>Subjects</head>
				<persname encodinganalog="600" rules="aacr2" role="subject">Davenport, Mildred,
	            1900-1990--Archives.</persname>
				<subject encodinganalog="650" source="lcsh">African American dancers--Archival
	            resources.</subject>
			</controlaccess>
			<controlaccess>
				<head>Occupations</head>
				<occupation encodinganalog="656" source="aat">Dancers.</occupation>
				<occupation encodinganalog="656" source="lcsh">Dance teachers.</occupation>
			</controlaccess>
		</controlaccess>
		
		<xsl:if test="boolean(REFD_LOWEREXIST)">
			<dsc type="combined">
				<!-- May contain: address, blockquote, c, c01, chronlist, dsc, head, list, note, p, table, thead -->

				<xsl:for-each select="LOWER_LEVEL">
					<xsl:variable name="lower_level_code" select="LOWER_CODE"/>

					<!-- recurse through the hierarchy -->
					<xsl:apply-templates select="//XML_RECORD[REFD=$lower_level_code]"/>
				</xsl:for-each>
			</dsc>
		</xsl:if>

	</xsl:template>
</xsl:stylesheet>